# Disable all cops by default
AllCops:
  DisabledByDefault: true
  Exclude:
    - 'test/unit/auto_instrument/*'
    - vendor/bundle/**/*

# 80 is stifling, especially with a few levels of nesting before we even start.
# So bump it to 100 to keep really long lines from creeping in.
Metrics/LineLength:
  Enabled: false
  Max: 100

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets
